name: app

type: php:8.2

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - ctype
        - iconv
        - pdo_mysql
        
build:
    flavor: none

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

disk: 512

mounts:
    "/var": { source: local, source_path: var }

hooks:
    build: |
        set -x -e
        curl -s https://get.symfony.com/cloud/configurator | bash
        symfony-build

    deploy: |
        set -x -e
        symfony-deploy